import { CATEGORY } from './colors';

// Each calculator gets a category accent (color + soft tint) plus a one-line
// description. Order roughly mirrors the design's tile grid.
export const CALCULATORS = [
  {
    id: 'home_loan',
    title: 'Home Loan',
    icon: 'home',
    description: 'EMI & total interest',
    color: CATEGORY.blue.c,
    softColor: CATEGORY.blue.soft,
    screen: 'HomeLoanCalculator',
  },
  {
    id: 'emi',
    title: 'EMI',
    icon: 'calculator',
    description: 'Repayment planner',
    color: CATEGORY.violet.c,
    softColor: CATEGORY.violet.soft,
    screen: 'EMICalculator',
  },
  {
    id: 'sip',
    title: 'SIP',
    icon: 'trending-up',
    description: 'Systematic investments',
    color: CATEGORY.green.c,
    softColor: CATEGORY.green.soft,
    screen: 'SIPCalculator',
  },
  {
    id: 'lumpsum',
    title: 'Lumpsum',
    icon: 'cash',
    description: 'One-time returns',
    color: CATEGORY.clay.c,
    softColor: CATEGORY.clay.soft,
    screen: 'LumpsumCalculator',
  },
  {
    id: 'fd',
    title: 'Fixed Deposit',
    icon: 'business',
    description: 'FD maturity',
    color: CATEGORY.teal.c,
    softColor: CATEGORY.teal.soft,
    screen: 'FDCalculator',
  },
  {
    id: 'rd',
    title: 'Recurring Dep.',
    icon: 'repeat',
    description: 'Monthly growth',
    color: CATEGORY.brown.c,
    softColor: CATEGORY.brown.soft,
    screen: 'RDCalculator',
  },
  {
    id: 'ppf',
    title: 'PPF',
    icon: 'shield-checkmark',
    description: '15-year PPF returns',
    color: CATEGORY.indigo.c,
    softColor: CATEGORY.indigo.soft,
    screen: 'PPFCalculator',
  },
  {
    id: 'tax',
    title: 'ITR Calculator',
    icon: 'receipt',
    description: 'Old vs New regime',
    color: CATEGORY.rose.c,
    softColor: CATEGORY.rose.soft,
    screen: 'TaxSavingsCalculator',
  },
  {
    id: 'goal',
    title: 'Goal Planner',
    icon: 'flag',
    description: 'Reach your goals',
    color: CATEGORY.amber.c,
    softColor: CATEGORY.amber.soft,
    screen: 'GoalPlannerCalculator',
  },
  {
    id: 'budget',
    title: 'Budget',
    icon: 'pie-chart',
    description: '50 / 30 / 20 plan',
    color: CATEGORY.orange.c,
    softColor: CATEGORY.orange.soft,
    screen: 'BudgetCalculator',
  },
];
